proxies:
- name: ID UNINET 07 09 2025
  type: trojan
  server: 104.22.5.240
  port: 443
  password: W79hqVWaHHS3ZB8Jrxbclg
  udp: true
  sni: ums2.xmd.asia
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /trojan-ws
  headers:
      Host: ums2.xmd.asia
